spring:
  security:
    user:
      name: test
      password: test
      
      
  application:
    name: Spring-Boot_Spring-MVC
    
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee_directory
    username: springstudent
    password: springstudent

    
countries: BRAZIL, INDIA, USA, CHINA
languages : GO, JAVA, Python, RUST
systems : Microsoft, Ubuntu, Linux, Kali Linux